export type ContentSourceStatus = "primary law" | "official guidance" | "official operational source" | "marketplace documentation";

export type ContentSource = {
  id: string;
  title: string;
  issuingAuthority: string;
  sourceType: "regulation" | "directive" | "German law" | "guidance" | "register" | "seller documentation";
  jurisdiction: string;
  url: string;
  legalIdentifier?: string;
  topics: string[];
  accessed: "2026-07-12";
  currentVersionDate?: string;
  notes: string;
  language: "English" | "German";
  status: ContentSourceStatus;
};

export const contentSources: ContentSource[] = [
  { id: "eu-gpsr", title: "General Product Safety Regulation", issuingAuthority: "European Union", sourceType: "regulation", jurisdiction: "European Union", url: "https://eur-lex.europa.eu/eli/reg/2023/988/oj", legalIdentifier: "Regulation (EU) 2023/988", topics: ["GPSR", "consumer products", "distance sales", "economic operators"], accessed: "2026-07-12", currentVersionDate: "2026-05-29", notes: "Horizontal consumer-product safety framework; product-specific Union legislation remains relevant.", language: "English", status: "primary law" },
  { id: "eu-market-surveillance", title: "Market surveillance and compliance of products", issuingAuthority: "European Union", sourceType: "regulation", jurisdiction: "European Union", url: "https://eur-lex.europa.eu/eli/reg/2019/1020/oj", legalIdentifier: "Regulation (EU) 2019/1020", topics: ["harmonised products", "economic operator", "authorised representative"], accessed: "2026-07-12", notes: "Article 4 applies to products covered by specified Union harmonisation legislation.", language: "English", status: "primary law" },
  { id: "eu-gpsr-guidelines", title: "Guidelines for businesses on the application of the GPSR", issuingAuthority: "European Commission", sourceType: "guidance", jurisdiction: "European Union", url: "https://eur-lex.europa.eu/eli/C/2025/6233/oj", legalIdentifier: "Commission Notice C/2025/6233", topics: ["GPSR", "responsible person", "fulfilment", "online marketplaces"], accessed: "2026-07-12", notes: "Official application guidance; does not replace the legal text.", language: "English", status: "official guidance" },
  { id: "eu-product-safety", title: "Product safety", issuingAuthority: "European Commission", sourceType: "guidance", jurisdiction: "European Union", url: "https://commission.europa.eu/topics/business-and-industry/doing-business-eu/eu-product-safety-and-labelling/product-safety_en", topics: ["product safety", "CE marking", "Safety Gate"], accessed: "2026-07-12", notes: "Official overview and links to product-specific rules.", language: "English", status: "official guidance" },
  { id: "eu-weee", title: "Waste electrical and electronic equipment", issuingAuthority: "European Union", sourceType: "directive", jurisdiction: "European Union", url: "https://eur-lex.europa.eu/eli/dir/2012/19/oj", legalIdentifier: "Directive 2012/19/EU", topics: ["WEEE", "producer responsibility", "take-back"], accessed: "2026-07-12", notes: "EU framework implemented through Member State law; registrations are national.", language: "English", status: "primary law" },
  { id: "de-elektrog", title: "Elektro- und Elektronikgerätegesetz", issuingAuthority: "Federal Ministry of Justice and Federal Office of Justice", sourceType: "German law", jurisdiction: "Germany", url: "https://www.gesetze-im-internet.de/elektrog_2015/", legalIdentifier: "ElektroG", topics: ["WEEE", "registration", "authorised representative", "guarantee", "reporting"], accessed: "2026-07-12", notes: "Current consolidated German law; manufacturer status depends on the statutory definitions.", language: "German", status: "primary law" },
  { id: "de-ear", title: "stiftung ear official portal", issuingAuthority: "stiftung elektro-altgeräte register", sourceType: "register", jurisdiction: "Germany", url: "https://www.stiftung-ear.de/en/", topics: ["ElektroG", "BattDG", "registration", "operational procedure"], accessed: "2026-07-12", notes: "The entrusted German authority and register, not a private certification body.", language: "English", status: "official operational source" },
  { id: "eu-batteries", title: "Batteries and waste batteries", issuingAuthority: "European Union", sourceType: "regulation", jurisdiction: "European Union", url: "https://eur-lex.europa.eu/eli/reg/2023/1542/oj", legalIdentifier: "Regulation (EU) 2023/1542", topics: ["batteries", "categories", "producer responsibility", "labelling", "battery passport"], accessed: "2026-07-12", notes: "Directly applicable framework with obligation-specific application and transition dates.", language: "English", status: "primary law" },
  { id: "de-battdg", title: "Batterierecht-Durchführungsgesetz", issuingAuthority: "Federal Ministry of Justice and Federal Office of Justice", sourceType: "German law", jurisdiction: "Germany", url: "https://www.gesetze-im-internet.de/battdg/", legalIdentifier: "BattDG", topics: ["battery registration", "producer responsibility organisations", "German administration", "transitions"], accessed: "2026-07-12", currentVersionDate: "2025-10-07", notes: "Replaced most of the former BattG from 7 October 2025; transition provisions must be checked for existing cases.", language: "German", status: "primary law" },
  { id: "de-verpackg", title: "Verpackungsgesetz", issuingAuthority: "Federal Ministry of Justice and Federal Office of Justice", sourceType: "German law", jurisdiction: "Germany", url: "https://www.gesetze-im-internet.de/verpackg/", legalIdentifier: "VerpackG", topics: ["packaging", "LUCID", "system participation", "data reporting"], accessed: "2026-07-12", notes: "Registration, system participation and reporting are distinct duties where applicable.", language: "German", status: "primary law" },
  { id: "eu-ppwr", title: "Packaging and Packaging Waste Regulation", issuingAuthority: "European Union", sourceType: "regulation", jurisdiction: "European Union", url: "https://eur-lex.europa.eu/eli/reg/2025/40/oj", legalIdentifier: "Regulation (EU) 2025/40", topics: ["packaging", "packaging waste", "producer responsibility", "future application"], accessed: "2026-07-12", currentVersionDate: "2025-01-22", notes: "In force and generally applies from 12 August 2026; content must be reviewed before that date and for provision-specific transitions.", language: "English", status: "primary law" },
  { id: "de-zsvr", title: "LUCID Packaging Register", issuingAuthority: "Zentrale Stelle Verpackungsregister (ZSVR)", sourceType: "register", jurisdiction: "Germany", url: "https://www.verpackungsregister.org/en/", topics: ["LUCID", "system participation", "packaging types", "marketplace checks"], accessed: "2026-07-12", notes: "Official register and operational guidance using ZSVR terminology.", language: "English", status: "official operational source" },
  { id: "eu-vat", title: "Common system of value added tax", issuingAuthority: "European Union", sourceType: "directive", jurisdiction: "European Union", url: "https://eur-lex.europa.eu/eli/dir/2006/112/oj", legalIdentifier: "Directive 2006/112/EC", topics: ["VAT", "place of supply", "distance sales", "special schemes"], accessed: "2026-07-12", notes: "VAT outcomes depend on transaction facts and implemented national law.", language: "English", status: "primary law" },
  { id: "de-ustg", title: "Umsatzsteuergesetz", issuingAuthority: "Federal Ministry of Justice and Federal Office of Justice", sourceType: "German law", jurisdiction: "Germany", url: "https://www.gesetze-im-internet.de/ustg_1980/", legalIdentifier: "UStG", topics: ["German VAT", "taxable transactions", "distance sales"], accessed: "2026-07-12", notes: "Use with transaction-specific tax advice where needed.", language: "German", status: "primary law" },
  { id: "de-bzst", title: "Federal Central Tax Office", issuingAuthority: "Bundeszentralamt für Steuern", sourceType: "guidance", jurisdiction: "Germany", url: "https://www.bzst.de/", topics: ["VAT procedures", "OSS", "tax identifiers"], accessed: "2026-07-12", notes: "Official tax-process portal; competent authority depends on the procedure.", language: "German", status: "official operational source" },
  { id: "de-gmbhg", title: "Gesetz betreffend die Gesellschaften mit beschränkter Haftung", issuingAuthority: "Federal Ministry of Justice and Federal Office of Justice", sourceType: "German law", jurisdiction: "Germany", url: "https://www.gesetze-im-internet.de/gmbhg/", legalIdentifier: "GmbHG", topics: ["GmbH", "UG", "formation", "notarial form", "registration"], accessed: "2026-07-12", notes: "Entity choice, capital and formation steps require case-specific professional review.", language: "German", status: "primary law" },
  { id: "de-startup", title: "Existenzgründungsportal", issuingAuthority: "Federal Ministry for Economic Affairs and Energy", sourceType: "guidance", jurisdiction: "Germany", url: "https://www.existenzgruendungsportal.de/", topics: ["company formation", "business planning", "professional support"], accessed: "2026-07-12", notes: "Official formation guidance; legal, notarial and tax services remain with qualified professionals.", language: "German", status: "official guidance" },
  { id: "de-commercial-register", title: "Common register portal of the German federal states", issuingAuthority: "German federal states' justice administrations", sourceType: "register", jurisdiction: "Germany", url: "https://www.handelsregister.de/", topics: ["commercial register", "company registration"], accessed: "2026-07-12", notes: "Official register access portal.", language: "English", status: "official operational source" },
  { id: "amazon-seller", title: "EU General Product Safety Regulation policy", issuingAuthority: "Amazon Seller Central", sourceType: "seller documentation", jurisdiction: "Amazon EU stores", url: "https://sellercentral.amazon.de/help/hub/reference/GQAYBJPNAZ2LMDDT", topics: ["Amazon", "GPSR", "listing information"], accessed: "2026-07-12", notes: "Login may be required. Marketplace policy is separate from legislation and may change independently.", language: "English", status: "marketplace documentation" },
  { id: "temu-seller", title: "Temu Seller Center", issuingAuthority: "Temu", sourceType: "seller documentation", jurisdiction: "Temu EU", url: "https://seller-eu.temu.com/login.html", topics: ["Temu", "seller onboarding", "seller documents"], accessed: "2026-07-12", notes: "Only current public onboarding information was reviewed; case requirements must be checked in the seller account.", language: "English", status: "marketplace documentation" },
  { id: "ebay-seller", title: "General Product Safety Regulation seller guidance", issuingAuthority: "eBay", sourceType: "seller documentation", jurisdiction: "eBay EU", url: "https://www.ebay.com/sellercenter/resources/general-product-safety-regulation", topics: ["eBay", "GPSR", "listing information"], accessed: "2026-07-12", notes: "Marketplace policy is separate from legislation and may change independently.", language: "English", status: "marketplace documentation" },
  { id: "shopify-gpsr", title: "Understanding the General Product Safety Regulation", issuingAuthority: "Shopify Help Center", sourceType: "seller documentation", jurisdiction: "Shopify merchants selling to the EU", url: "https://help.shopify.com/en/manual/international/gpsr", topics: ["Shopify", "GPSR", "store information"], accessed: "2026-07-12", notes: "Platform guidance, not legal advice or an authority decision.", language: "English", status: "marketplace documentation" },
];

const sourceById = new Map(contentSources.map((source) => [source.id, source]));
export function getContentSources(ids: string[]) { return ids.map((id) => sourceById.get(id)).filter((source): source is ContentSource => Boolean(source)); }
