insert into public.services
  (slug, name, category, short_description, who_needs_it, required_information, required_documents, process_steps, display_order)
values
  ('company-formation-germany', 'Open a company in Germany', 'market-entry', 'Structured support for founders preparing a German GmbH or UG setup.', 'Foreign sellers who want a German legal presence, local credibility, or a stronger EU operating base.', '["Founder details","Shareholder structure","Business activity","Desired company name"]', '["Founder passport","Proof of address","Business activity description","Shareholder information"]', '["Scope the setup","Prepare formation checklist","Coordinate address and VAT needs","Prepare next actions"]', 10),
  ('german-business-address', 'German business address support', 'market-entry', 'Address support for companies building a German market-entry presence.', 'Sellers who need a reliable German address for setup, correspondence, or marketplace onboarding.', '["Company details","Intended use","Expected mail volume"]', '["Company documents","Representative ID"]', '["Confirm use case","Review eligibility","Prepare address support path"]', 20),
  ('vat-registration-germany', 'VAT registration support', 'market-entry', 'German VAT number and filing coordination for foreign sellers.', 'Companies selling taxable goods in Germany or holding stock in Germany.', '["Company country","Sales channels","Sales estimates","Existing VAT status"]', '["Business license","Tax certificate if available","Marketplace seller details"]', '["Check VAT trigger","Collect documents","Coordinate application and filing path"]', 30),
  ('bookkeeping-tax-coordination', 'Bookkeeping / tax coordination', 'market-entry', 'Coordination for bookkeeping, monthly filing needs, and German tax workflows.', 'Sellers who need ongoing tax coordination after VAT registration or company formation.', '["Sales channels","Transaction volume","Existing advisor status"]', '["Company documents","VAT documents","Marketplace reports"]', '["Assess volume","Prepare bookkeeping workflow","Coordinate recurring filing support"]', 40),
  ('marketplace-seller-setup', 'Marketplace seller setup support', 'market-entry', 'Setup support for sellers entering Amazon, Temu, eBay, Shopify, or other channels.', 'Companies opening or regularizing marketplace accounts for Germany.', '["Marketplace names","Seller account country","Product categories"]', '["Company documents","VAT details","Compliance registrations"]', '["Review channel requirements","Map missing documents","Prepare onboarding checklist"]', 50),
  ('weee-elektrog-registration', 'WEEE / ElektroG registration', 'compliance', 'Registration support for electrical and electronic products sold in Germany.', 'Sellers offering electrical or electronic equipment under their brand in Germany.', '["Brand","Device category","B2B/B2C status","Yearly quantity"]', '["Business license","Product photos","Label photos","Manual","Brand information"]', '["Classify product","Review brand/device data","Prepare registration path","Support marketplace evidence"]', 110),
  ('battery-battg-registration', 'Battery / BattG registration', 'compliance', 'Battery registration support for products containing or shipping with batteries.', 'Sellers placing batteries, built-in batteries, or battery-powered products on the German market.', '["Battery type","Chemistry","Weight","Estimated yearly quantity"]', '["Product photos","Battery specification","Existing registration if any"]', '["Identify battery obligation","Collect technical data","Prepare registration support"]', 120),
  ('packaging-verpackg-lucid', 'Packaging / VerpackG / LUCID registration', 'compliance', 'Packaging registration and system participation coordination for Germany.', 'Sellers shipping packaged products to German end customers.', '["Packaging materials","Packaging quantity","Marketplace used","Existing LUCID status"]', '["Company documents","Packaging estimates","Marketplace details"]', '["Check VerpackG obligation","Prepare LUCID and system data","Document marketplace proof"]', 130),
  ('gpsr-eu-responsible-person', 'EU Responsible Person / GPSR service', 'compliance', 'Support for GPSR Responsible Person needs and product documentation review.', 'Non-EU sellers placing consumer products on EU marketplaces or facing GPSR document requests.', '["Manufacturer details","Product category","Marketplace link","Urgency and deadlines"]', '["Product photos","Label photos","DoC","Test reports","User manual","Risk assessment"]', '["Review product documents","Identify missing evidence","Prepare Responsible Person path"]', 140),
  ('product-compliance-review', 'Product compliance document review', 'compliance', 'Review product photos, labels, manuals, test reports, and marketplace compliance requests.', 'Sellers unsure whether product documentation is ready for Germany or EU marketplaces.', '["Product category","Marketplace","Documents requested","Deadline"]', '["Product photos","Label photos","Manual","Test reports","Declarations"]', '["Review submitted documents","Flag gaps","Prepare next-step checklist"]', 150),
  ('declaration-of-conformity-review', 'Declaration of Conformity review', 'compliance', 'Review DoC structure and product-document alignment for applicable products.', 'Sellers asked by marketplaces or authorities to provide a Declaration of Conformity.', '["Product category","Standards referenced","Manufacturer details"]', '["Declaration of Conformity","Test reports","Manual","Label photos"]', '["Check DoC completeness","Compare with evidence","Prepare correction notes"]', 160),
  ('test-report-review', 'Test report review', 'compliance', 'Review test reports against marketplace or product compliance expectations.', 'Sellers with test reports who need to understand whether the documents fit German/EU requirements.', '["Product category","Standards","Marketplace issue if any"]', '["Test reports","Product photos","Manual","Marketplace notice"]', '["Review report scope","Check product match","Summarize gaps"]', 170),
  ('marketplace-compliance-support', 'Marketplace compliance support', 'compliance', 'Support for missing compliance documents, blocked listings, and marketplace requests.', 'Sellers with urgent marketplace compliance warnings, missing-document cases, or listing blocks.', '["Marketplace","Case ID","Product link","Documents requested","Deadline"]', '["Screenshots","Emails/notices","Product documents","Registration proof"]', '["Review notice","Map required documents","Prepare response package"]', 180),
  ('authority-case-support', 'Authority case support', 'compliance', 'Structured intake for urgent German authority or official compliance cases.', 'Companies contacted by authorities or facing deadlines for product, tax, or registration evidence.', '["Authority name","Deadline","Case summary","Products affected"]', '["Authority letter","Product documents","Company documents","Prior correspondence"]', '["Review case documents","Prioritize deadline","Prepare next actions"]', 190),
  ('warehouse-storage-germany', 'Storage / Einlagerung', 'warehouse', 'German warehouse storage intake for cartons, pallets, marketplace stock, and prepared goods.', 'Foreign sellers who need stock held in Germany before marketplace delivery or onward shipment.', '["Product type","Carton/pallet count","Dimensions","Weights","Storage duration"]', '["Packing list","Product photos","Delivery documents"]', '["Review stock profile","Confirm handling needs","Plan inbound and outbound steps"]', 210),
  ('packing-service', 'Packing service', 'warehouse', 'Packing support for units, cartons, marketplace shipments, or relaunch preparation.', 'Sellers whose products need packing before delivery to marketplaces or customers.', '["Unit count","Packaging needs","Deadline","Outbound destination"]', '["Product photos","Packing instructions","Label files"]', '["Confirm packing scope","Review materials and labels","Prepare packing schedule"]', 220),
  ('repacking-umverpackung', 'Repacking / Umverpackung', 'warehouse', 'Repacking for products that need German/EU-ready presentation or marketplace-ready cartons.', 'Sellers with packaging issues, damaged outer packaging, or marketplace preparation needs.', '["Units","Current packaging issue","Target packaging","Deadline"]', '["Product photos","Packaging photos","Instructions","Label files"]', '["Review current packaging","Define repacking method","Prepare handling timeline"]', 230),
  ('relabeling-umlabeln', 'Relabeling / Umlabeln', 'warehouse', 'Relabeling for barcode, compliance, marketplace, or product label corrections.', 'Sellers whose goods need new labels before entering marketplaces.', '["Unit count","Label type","Current issue","Deadline"]', '["Label file","Product photos","Current label photos"]', '["Check label files","Confirm unit count","Plan relabeling and quality check"]', 240),
  ('barcode-fnsku-labeling', 'Barcode / FNSKU labeling', 'warehouse', 'Barcode, FNSKU, and marketplace label application for prepared stock.', 'Sellers preparing inventory for Amazon FBA or barcode-driven marketplaces.', '["Unit count","Label format","SKU/ASIN","Deadline"]', '["Barcode/FNSKU files","Product photos","Packing list"]', '["Validate label files","Confirm application rules","Apply labels and prepare stock"]', 250),
  ('product-inspection', 'Product inspection', 'warehouse', 'Product inspection intake for checking stock condition, labels, packaging, or samples.', 'Sellers who need a German-side check before forwarding goods.', '["Inspection objective","Unit/carton count","Photos required","Deadline"]', '["Packing list","Product photos","Inspection checklist"]', '["Define inspection scope","Inspect sample or stock","Report findings"]', 260),
  ('return-handling', 'Return handling', 'warehouse', 'Handling returned goods in Germany with inspection, relabeling, repacking, or onward shipment.', 'Sellers needing a German return address or structured return processing support.', '["Return volume","Product type","Inspection rules","Disposition plan"]', '["Return instructions","Product photos","Marketplace return documents"]', '["Confirm return flow","Inspect received goods","Prepare disposition options"]', 270),
  ('shipment-preparation', 'Shipment preparation', 'warehouse', 'Preparation for outbound marketplace, customer, or partner shipments from German stock.', 'Sellers needing cartons, pallets, labels, or documents prepared before outbound forwarding.', '["Destination","Stock details","Shipping labels","Deadline"]', '["Shipping labels","Packing list","Commercial documents"]', '["Confirm shipment rules","Prepare goods","Handover to carrier"]', 280),
  ('amazon-compliance-support', 'Amazon compliance support', 'marketplace', 'Support for Amazon Germany/EU compliance document requests, ASIN cases, and listing blocks.', 'Amazon sellers with missing document cases, WEEE/BattG/VerpackG/GPSR requests, or urgent listing issues.', '["ASIN/SKU","Case ID","Marketplace notice","Deadline"]', '["Screenshots/notices","Product documents","Registration proof","Labels"]', '["Review case","Identify required proof","Prepare response package"]', 310),
  ('temu-compliance-support', 'Temu compliance support', 'marketplace', 'Document and case support for Temu sellers preparing or maintaining German/EU listings.', 'Temu sellers asked for product, compliance, or seller documentation.', '["Product link","Case or notice details","Documents requested"]', '["Screenshots/notices","Product documents","Company documents"]', '["Review request","Map missing documents","Prepare response"]', 320),
  ('aliexpress-support', 'AliExpress support', 'marketplace', 'German/EU document preparation support for AliExpress sellers.', 'AliExpress sellers entering Germany or resolving document gaps.', '["Product link","Seller account country","Issue details"]', '["Product documents","Marketplace screenshots","Company details"]', '["Review marketplace need","Collect missing data","Prepare documentation path"]', 330),
  ('ebay-support', 'eBay support', 'marketplace', 'Support for eBay Germany compliance, product document, and seller setup needs.', 'eBay sellers selling physical products in Germany.', '["Listing link","Product category","Document request"]', '["Product documents","Registration proof","Marketplace messages"]', '["Review listing and request","Identify obligations","Prepare response"]', 340),
  ('shopify-support', 'Shopify support', 'marketplace', 'Support for Shopify sellers preparing compliance, VAT, storage, and Germany-ready operations.', 'Direct-to-consumer sellers using Shopify to sell packaged physical products in Germany.', '["Store URL","Product categories","Fulfillment model","VAT/compliance status"]', '["Company documents","Product documents","Packaging estimates"]', '["Review store model","Map triggers","Prepare launch checklist"]', 350),
  ('product-listing-document-support', 'Product listing document support', 'marketplace', 'Prepare product listing documentation before launch or after document requests.', 'Sellers whose listings need product documents, compliance proof, labels, or manuals.', '["Marketplace","Product link","Documents requested","Deadline"]', '["Product photos","Labels","Manuals","Test reports","Registration proof"]', '["Review listing need","Create document checklist","Prepare upload-ready package"]', 360),
  ('marketplace-suspension-support', 'Marketplace suspension / missing document support', 'marketplace', 'Urgent support for suspended listings, missing documents, and compliance-driven cases.', 'Sellers facing account, listing, or product restrictions because documents are missing or unclear.', '["Marketplace","Case ID","Suspension reason","Deadline"]', '["Screenshots","Emails/notices","Requested documents","Product compliance files"]', '["Triage urgency","Review missing evidence","Prepare response plan"]', 370)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  short_description = excluded.short_description,
  who_needs_it = excluded.who_needs_it,
  required_information = excluded.required_information,
  required_documents = excluded.required_documents,
  process_steps = excluded.process_steps,
  display_order = excluded.display_order,
  updated_at = now();

with template_questions(template, question_key, label, question_type, options, required, display_order) as (
  values
  ('formation', 'founder_name', 'Founder name', 'text', '[]'::jsonb, true, 10),
  ('formation', 'company_type', 'Desired company type', 'select', '["GmbH","UG","Not sure"]'::jsonb, false, 20),
  ('formation', 'business_activity', 'Desired business activity', 'textarea', '[]'::jsonb, false, 30),
  ('formation', 'business_address', 'Need German business address?', 'yes_no', '[]'::jsonb, false, 40),
  ('formation', 'vat_registration', 'Need VAT registration?', 'yes_no', '[]'::jsonb, false, 50),
  ('vat', 'existing_company_country', 'Existing company country', 'text', '[]'::jsonb, false, 10),
  ('vat', 'existing_vat_number', 'Existing VAT number', 'text', '[]'::jsonb, false, 20),
  ('vat', 'need_german_vat', 'Need German VAT number?', 'yes_no', '[]'::jsonb, false, 30),
  ('vat', 'sales_channels', 'Sales channels', 'multiselect', '["Amazon","Temu","AliExpress","eBay","Shopify","Other"]'::jsonb, false, 40),
  ('weee', 'product_type', 'Product type', 'text', '[]'::jsonb, true, 10),
  ('weee', 'electrical_category', 'Electrical/electronic category', 'text', '[]'::jsonb, false, 20),
  ('weee', 'brand_name', 'Brand name', 'text', '[]'::jsonb, false, 30),
  ('weee', 'battery_included', 'Battery included?', 'yes_no', '[]'::jsonb, false, 40),
  ('battery', 'battery_type', 'Battery type', 'text', '[]'::jsonb, false, 10),
  ('battery', 'battery_chemistry', 'Battery chemistry', 'text', '[]'::jsonb, false, 20),
  ('battery', 'battery_weight', 'Battery weight per unit', 'text', '[]'::jsonb, false, 30),
  ('packaging', 'packaging_type', 'Packaging type', 'text', '[]'::jsonb, false, 10),
  ('packaging', 'packaging_material', 'Packaging material', 'text', '[]'::jsonb, false, 20),
  ('packaging', 'lucid_number', 'Existing LUCID number?', 'yes_no', '[]'::jsonb, false, 30),
  ('gpsr', 'manufacturer_name', 'Manufacturer name', 'text', '[]'::jsonb, false, 10),
  ('gpsr', 'manufacturer_address', 'Manufacturer address', 'textarea', '[]'::jsonb, false, 20),
  ('gpsr', 'doc_available', 'Declaration of Conformity available?', 'yes_no', '[]'::jsonb, false, 30),
  ('gpsr', 'test_reports_available', 'Test reports available?', 'yes_no', '[]'::jsonb, false, 40),
  ('warehouse', 'cartons', 'Number of cartons', 'number', '[]'::jsonb, false, 10),
  ('warehouse', 'pallets', 'Number of pallets', 'number', '[]'::jsonb, false, 20),
  ('warehouse', 'storage_duration', 'Storage duration', 'text', '[]'::jsonb, false, 30),
  ('warehouse', 'delivery_date', 'Delivery date', 'date', '[]'::jsonb, false, 40),
  ('warehouse', 'relabeling_needed', 'Need relabeling?', 'yes_no', '[]'::jsonb, false, 50),
  ('relabeling', 'units', 'Number of units', 'number', '[]'::jsonb, false, 10),
  ('relabeling', 'label_type', 'Label type', 'select', '["Barcode","FNSKU","Product label","Warning label","Other"]'::jsonb, false, 20),
  ('relabeling', 'label_file', 'Upload label file', 'file', '[]'::jsonb, false, 30),
  ('marketplace', 'marketplace_name', 'Marketplace name', 'select', '["Amazon","Temu","AliExpress","eBay","Shopify","Other"]'::jsonb, false, 10),
  ('marketplace', 'product_link', 'Product link', 'text', '[]'::jsonb, false, 20),
  ('marketplace', 'case_id', 'Case ID', 'text', '[]'::jsonb, false, 30),
  ('marketplace', 'requested_documents', 'Documents requested by marketplace', 'textarea', '[]'::jsonb, false, 40)
),
service_templates(service_slug, template) as (
  values
  ('company-formation-germany', 'formation'),
  ('german-business-address', 'formation'),
  ('vat-registration-germany', 'vat'),
  ('bookkeeping-tax-coordination', 'vat'),
  ('marketplace-seller-setup', 'marketplace'),
  ('weee-elektrog-registration', 'weee'),
  ('battery-battg-registration', 'battery'),
  ('packaging-verpackg-lucid', 'packaging'),
  ('gpsr-eu-responsible-person', 'gpsr'),
  ('product-compliance-review', 'gpsr'),
  ('declaration-of-conformity-review', 'gpsr'),
  ('test-report-review', 'gpsr'),
  ('marketplace-compliance-support', 'marketplace'),
  ('authority-case-support', 'marketplace'),
  ('warehouse-storage-germany', 'warehouse'),
  ('packing-service', 'warehouse'),
  ('repacking-umverpackung', 'warehouse'),
  ('relabeling-umlabeln', 'relabeling'),
  ('barcode-fnsku-labeling', 'relabeling'),
  ('product-inspection', 'warehouse'),
  ('return-handling', 'warehouse'),
  ('shipment-preparation', 'warehouse'),
  ('amazon-compliance-support', 'marketplace'),
  ('temu-compliance-support', 'marketplace'),
  ('aliexpress-support', 'marketplace'),
  ('ebay-support', 'marketplace'),
  ('shopify-support', 'marketplace'),
  ('product-listing-document-support', 'marketplace'),
  ('marketplace-suspension-support', 'marketplace')
)
insert into public.service_questions
  (service_slug, question_key, label, question_type, options, required, display_order)
select st.service_slug, tq.question_key, tq.label, tq.question_type, tq.options, tq.required, tq.display_order
from service_templates st
join template_questions tq on tq.template = st.template
on conflict (service_slug, question_key) do update set
  label = excluded.label,
  question_type = excluded.question_type,
  options = excluded.options,
  required = excluded.required,
  display_order = excluded.display_order,
  updated_at = now();
