insert into public.services
  (slug, name, category, short_description, who_needs_it, required_information, required_documents, process_steps, display_order)
values
  ('company-formation-germany', 'Open a company in Germany', 'market-entry', 'Structured support for founders preparing a German GmbH or UG setup.', 'Foreign sellers who want a German legal presence, local credibility, or a stronger EU operating base.', '["Founder details","Shareholder structure","Business activity","Desired company name"]', '["Founder passport","Proof of address","Business activity description","Shareholder information"]', '["Scope the setup","Prepare formation checklist","Coordinate address and VAT needs","Prepare next actions"]', 10),
  ('german-business-address', 'German business address support', 'market-entry', 'Address support for companies building a German market-entry presence.', 'Sellers who need a reliable German address for setup, correspondence, or marketplace onboarding.', '["Company details","Intended use","Expected mail volume"]', '["Company documents","Representative ID"]', '["Confirm use case","Review eligibility","Prepare address support path"]', 20),
  ('vat-registration-germany', 'VAT registration support', 'market-entry', 'German VAT number and filing coordination for foreign sellers.', 'Companies selling taxable goods in Germany or holding stock in Germany.', '["Company country","Sales channels","Sales estimates","Existing VAT status"]', '["Business license","Tax certificate if available","Marketplace seller details"]', '["Check VAT trigger","Collect documents","Coordinate application and filing path"]', 30),
  ('bookkeeping-tax-coordination', 'Bookkeeping / tax coordination', 'market-entry', 'Coordination for bookkeeping, monthly filing needs, and German tax workflows.', 'Sellers who need ongoing tax coordination after VAT registration or company formation.', '["Sales channels","Transaction volume","Existing advisor status"]', '["Company documents","VAT documents","Marketplace reports"]', '["Assess volume","Prepare bookkeeping workflow","Coordinate recurring filing support"]', 40),
  ('marketplace-seller-setup', 'Marketplace seller setup support', 'market-entry', 'Setup support for sellers entering Amazon, Temu, eBay, Shopify, or other channels.', 'Companies opening or regularizing marketplace accounts for Germany.', '["Marketplace names","Seller account country","Product categories"]', '["Company documents","VAT details","Compliance registrations"]', '["Review channel requirements","Map missing documents","Prepare onboarding checklist"]', 50),
  ('weee-elektrog-registration', 'WEEE / ElektroG registration', 'compliance', 'Registration support for electrical and electronic products sold in Germany.', 'Sellers offering electrical or electronic equipment under their brand in Germany.', '["Brand","Device category","B2B/B2C status","Yearly quantity"]', '["Business license","Product photos","Label photos","Manual","Brand information"]', '["Classify product","Review brand/device data","Prepare registration path","Support marketplace evidence"]', 110),
  ('battery-battg-registration', 'Battery / BattG registration', 'compliance', 'Battery registration support for products containing or shipping with batteries.', 'Sellers placing batteries, built-in batteries, or battery-powered products on the German market.', '["Battery type","Chemistry","Weight","Estimated yearly quantity"]', '["Product photos","Battery specification","Existing registration if any"]', '["Identify battery obligation","Collect technical data","Prepare registration support"]', 120),
  ('packaging-verpackg-lucid', 'Packaging / VerpackG / LUCID registration', 'compliance', 'Packaging registration and system participation coordination for Germany.', 'Sellers shipping packaged products to German end customers.', '["Packaging materials","Packaging quantity","Marketplace used","Existing LUCID status"]', '["Company documents","Packaging estimates","Marketplace details"]', '["Check VerpackG obligation","Prepare LUCID and system data","Document marketplace proof"]', 130),
  ('gpsr-eu-responsible-person', 'EU Responsible Person / GPSR service', 'compliance', 'Support for GPSR Responsible Person needs and product documentation review.', 'Non-EU sellers placing consumer products on EU marketplaces or facing GPSR document requests.', '["Manufacturer details","Product category","Marketplace link","Urgency and deadlines"]', '["Product photos","Label photos","DoC","Test reports","User manual","Risk assessment"]', '["Review product documents","Identify missing evidence","Prepare Responsible Person path"]', 140),
  ('product-compliance-review', 'Product compliance document review', 'compliance', 'Review product photos, labels, manuals, test reports, and marketplace compliance requests.', 'Sellers unsure whether product documentation is ready for Germany or EU marketplaces.', '["Product category","Marketplace","Documents requested","Deadline"]', '["Product photos","Label photos","Manual","Test reports","Declarations"]', '["Review submitted documents","Flag gaps","Prepare next-step checklist"]', 150),
  ('declaration-of-conformity-review', 'Declaration of Conformity review', 'compliance', 'Review DoC structure and product-document alignment for applicable products.', 'Sellers asked by marketplaces or authorities to provide a Declaration of Conformity.', '["Product category","Standards referenced","Manufacturer details"]', '["Declaration of Conformity","Test reports","Manual","Label photos"]', '["Check DoC completeness","Compare with evidence","Prepare correction notes"]', 160),
  ('test-report-review', 'Test report review', 'compliance', 'Review test reports against marketplace or product compliance expectations.', 'Sellers with test reports who need to understand whether the documents fit German/EU requirements.', '["Product category","Standards","Marketplace issue if any"]', '["Test reports","Product photos","Manual","Marketplace notice"]', '["Review report scope","Check product match","Summarize gaps"]', 170),
  ('marketplace-compliance-support', 'Marketplace compliance support', 'compliance', 'Support for missing compliance documents, blocked listings, and marketplace requests.', 'Sellers with urgent marketplace compliance warnings, missing-document cases, or listing blocks.', '["Marketplace","Case ID","Product link","Documents requested","Deadline"]', '["Screenshots","Emails/notices","Product documents","Registration proof"]', '["Review notice","Map required documents","Prepare response package"]', 180),
  ('authority-case-support', 'Authority case support', 'compliance', 'Structured intake for urgent German authority or official compliance cases.', 'Companies contacted by authorities or facing deadlines for product, tax, or registration evidence.', '["Authority name","Deadline","Case summary","Products affected"]', '["Authority letter","Product documents","Company documents","Prior correspondence"]', '["Review case documents","Prioritize deadline","Prepare next actions"]', 190),
  ('warehouse-storage-germany', 'Storage / Einlagerung', 'warehouse', 'German warehouse storage intake for cartons, pallets, marketplace stock, and prepared goods.', 'Foreign sellers who need stock held in Germany before marketplace delivery or onward shipment.', '["Product type","Carton/pallet count","Dimensions","Weights","Storage duration"]', '["Packing list","Product photos","Delivery documents"]', '["Review stock profile","Confirm handling needs","Plan inbound and outbound steps"]', 210),
  ('packing-service', 'Packing service', 'warehouse', 'Packing support for units, cartons, marketplace shipments, or relaunch preparation.', 'Sellers whose products need packing before delivery to marketplaces or customers.', '["Unit count","Packaging needs","Deadline","Outbound destination"]', '["Product photos","Packing instructions","Label files"]', '["Confirm packing scope","Review materials and labels","Prepare packing schedule"]', 220),
  ('repacking-umverpackung', 'Repacking / Umverpackung', 'warehouse', 'Repacking for products that need German/EU-ready presentation or marketplace-ready cartons.', 'Sellers with packaging issues, damaged outer packaging, or marketplace preparation needs.', '["Units","Current packaging issue","Target packaging","Deadline"]', '["Product photos","Packaging photos","Instructions","Label files"]', '["Review current packaging","Define repacking method","Prepare handling timeline"]', 230),
  ('relabeling-umlabeln', 'Relabeling / Umlabeln', 'warehouse', 'Relabeling for barcode, compliance, marketplace, or product label corrections.', 'Sellers whose goods need new labels before entering marketplaces.', '["Unit count","Label type","Current issue","Deadline"]', '["Label file","Product photos","Current label photos"]', '["Check label files","Confirm unit count","Plan relabeling and quality check"]', 240),
  ('barcode-fnsku-labeling', 'Barcode / FNSKU labeling', 'warehouse', 'Barcode, FNSKU, and marketplace label application for prepared stock.', 'Sellers preparing inventory for Amazon FBA or barcode-driven marketplaces.', '["Unit count","Label format","SKU/ASIN","Deadline"]', '["Barcode/FNSKU files","Product photos","Packing list"]', '["Validate label files","Confirm application rules","Apply labels and prepare stock"]', 250),
  ('product-inspection', 'Product inspection', 'warehouse', 'Product inspection intake for checking stock condition, labels, packaging, or samples.', 'Sellers who need a German-side check before forwarding goods.', '["Inspection objective","Unit/carton count","Photos required","Deadline"]', '["Packing list","Product photos","Inspection checklist"]', '["Define inspection scope","Inspect sample or stock","Report findings"]', 260),
  ('return-handling', 'Return handling', 'warehouse', 'Handling returned goods in Germany with inspection, relabeling, repacking, or onward shipment.', 'Sellers needing a German return address or structured return processing support.', '["Return volume","Product type","Inspection rules","Disposition plan"]', '["Return instructions","Product photos","Marketplace return documents"]', '["Confirm return flow","Inspect received goods","Prepare disposition options"]', 270),
  ('shipment-preparation', 'Shipment preparation', 'warehouse', 'Preparation for outbound marketplace, customer, or partner shipments from German stock.', 'Sellers needing cartons, pallets, labels, or documents prepared before outbound forwarding.', '["Destination","Stock details","Shipping labels","Deadline"]', '["Shipping labels","Packing list","Commercial documents"]', '["Confirm shipment rules","Prepare goods","Handover to carrier"]', 280),
  ('amazon-compliance-support', 'Amazon compliance support', 'marketplace', 'Support for Amazon Germany/EU compliance document requests, ASIN cases, and listing blocks.', 'Amazon sellers with missing document cases, WEEE/BattG/VerpackG/GPSR requests, or urgent listing issues.', '["ASIN/SKU","Case ID","Marketplace notice","Deadline"]', '["Screenshots/notices","Product documents","Registration proof","Labels"]', '["Review case","Identify required proof","Prepare response package"]', 310),
  ('temu-compliance-support', 'Temu compliance support', 'marketplace', 'Document and case support for Temu sellers preparing or maintaining German/EU listings.', 'Temu sellers asked for product, compliance, or seller documentation.', '["Product link","Case or notice details","Documents requested"]', '["Screenshots/notices","Product documents","Company documents"]', '["Review request","Map missing documents","Prepare response"]', 320),
  ('aliexpress-support', 'AliExpress support', 'marketplace', 'German/EU document preparation support for AliExpress sellers.', 'AliExpress sellers entering Germany or resolving document gaps.', '["Product link","Seller account country","Issue details"]', '["Product documents","Marketplace screenshots","Company details"]', '["Review marketplace need","Collect missing data","Prepare documentation path"]', 330),
  ('ebay-support', 'eBay support', 'marketplace', 'Support for eBay Germany compliance, product document, and seller setup needs.', 'eBay sellers selling physical products in Germany.', '["Listing link","Product category","Document request"]', '["Product documents","Registration proof","Marketplace messages"]', '["Review listing and request","Identify obligations","Prepare response"]', 340),
  ('shopify-support', 'Shopify support', 'marketplace', 'Support for Shopify sellers preparing compliance, VAT, storage, and Germany-ready operations.', 'Direct-to-consumer sellers using Shopify to sell packaged physical products in Germany.', '["Store URL","Product categories","Fulfillment model","VAT/compliance status"]', '["Company documents","Product documents","Packaging estimates"]', '["Review store model","Map triggers","Prepare launch checklist"]', 350),
  ('product-listing-document-support', 'Product listing document support', 'marketplace', 'Prepare product listing documentation before launch or after document requests.', 'Sellers whose listings need product documents, compliance proof, labels, or manuals.', '["Marketplace","Product link","Documents requested","Deadline"]', '["Product photos","Labels","Manuals","Test reports","Registration proof"]', '["Review listing need","Create document checklist","Prepare upload-ready package"]', 360),
  ('marketplace-suspension-support', 'Marketplace suspension / missing document support', 'marketplace', 'Urgent support for suspended listings, missing documents, and compliance-driven cases.', 'Sellers facing account, listing, or product restrictions because documents are missing or unclear.', '["Marketplace","Case ID","Suspension reason","Deadline"]', '["Screenshots","Emails/notices","Requested documents","Product compliance files"]', '["Triage urgency","Review missing evidence","Prepare response plan"]', 370)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  short_description = excluded.short_description,
  who_needs_it = excluded.who_needs_it,
  required_information = excluded.required_information,
  required_documents = excluded.required_documents,
  process_steps = excluded.process_steps,
  display_order = excluded.display_order,
  updated_at = now();

with template_questions(template, question_key, label, question_type, options, required, display_order) as (
  values
  ('formation', 'founder_name', 'Founder name', 'text', '[]'::jsonb, true, 10),
  ('formation', 'founder_nationality', 'Founder nationality', 'text', '[]'::jsonb, false, 20),
  ('formation', 'shareholders', 'Number of shareholders', 'number', '[]'::jsonb, false, 30),
  ('formation', 'company_type', 'Desired company type', 'select', '["GmbH","UG","Not sure"]'::jsonb, false, 40),
  ('formation', 'business_activity', 'Desired business activity', 'textarea', '[]'::jsonb, false, 50),
  ('formation', 'business_address', 'Need German business address?', 'yes_no', '[]'::jsonb, false, 60),
  ('formation', 'vat_registration', 'Need VAT registration?', 'yes_no', '[]'::jsonb, false, 70),
  ('formation', 'bookkeeping', 'Need bookkeeping support?', 'yes_no', '[]'::jsonb, false, 80),
  ('formation', 'bank_account', 'Need bank account support?', 'yes_no', '[]'::jsonb, false, 90),
  ('formation', 'preferred_company_name', 'Preferred company name', 'text', '[]'::jsonb, false, 100),
  ('formation', 'desired_start_date', 'Desired start date', 'date', '[]'::jsonb, false, 110),
  ('vat', 'existing_company_country', 'Existing company country', 'text', '[]'::jsonb, false, 10),
  ('vat', 'existing_vat_number', 'Existing VAT number', 'text', '[]'::jsonb, false, 20),
  ('vat', 'need_german_vat', 'Need German VAT number?', 'yes_no', '[]'::jsonb, false, 30),
  ('vat', 'sales_channels', 'Sales channels', 'multiselect', '["Amazon","Temu","AliExpress","eBay","Shopify","Other"]'::jsonb, false, 40),
  ('vat', 'monthly_sales_estimate', 'Monthly sales estimate', 'text', '[]'::jsonb, false, 50),
  ('vat', 'monthly_filing', 'Need monthly filing?', 'yes_no', '[]'::jsonb, false, 60),
  ('vat', 'tax_advisor', 'Existing tax advisor?', 'yes_no', '[]'::jsonb, false, 70),
  ('vat', 'bookkeeping_support', 'Need bookkeeping support?', 'yes_no', '[]'::jsonb, false, 80),
  ('weee', 'product_type', 'Product type', 'text', '[]'::jsonb, true, 10),
  ('weee', 'electrical_category', 'Electrical/electronic category', 'text', '[]'::jsonb, false, 20),
  ('weee', 'brand_name', 'Brand name', 'text', '[]'::jsonb, false, 30),
  ('weee', 'device_type', 'Device type', 'text', '[]'::jsonb, false, 40),
  ('weee', 'b2b_b2c', 'B2B or B2C', 'select', '["B2B","B2C","Both","Not sure"]'::jsonb, false, 50),
  ('weee', 'yearly_quantity', 'Estimated yearly quantity', 'number', '[]'::jsonb, false, 60),
  ('weee', 'battery_included', 'Battery included?', 'yes_no', '[]'::jsonb, false, 70),
  ('weee', 'existing_weee', 'Existing WEEE registration?', 'yes_no', '[]'::jsonb, false, 80),
  ('weee', 'weee_number', 'Existing WEEE number', 'text', '[]'::jsonb, false, 90),
  ('weee', 'marketplace_link', 'Marketplace link', 'text', '[]'::jsonb, false, 100),
  ('battery', 'battery_type', 'Battery type', 'text', '[]'::jsonb, false, 10),
  ('battery', 'battery_chemistry', 'Battery chemistry', 'text', '[]'::jsonb, false, 20),
  ('battery', 'battery_installation', 'Built-in or separate battery', 'select', '["Built-in","Separate","Both","Not sure"]'::jsonb, false, 30),
  ('battery', 'battery_weight', 'Battery weight per unit', 'text', '[]'::jsonb, false, 40),
  ('battery', 'battery_quantity', 'Estimated yearly battery quantity', 'number', '[]'::jsonb, false, 50),
  ('battery', 'battery_product', 'Product linked to battery', 'text', '[]'::jsonb, false, 60),
  ('battery', 'existing_battery_registration', 'Existing battery registration?', 'yes_no', '[]'::jsonb, false, 70),
  ('battery', 'battery_registration_number', 'Existing registration number', 'text', '[]'::jsonb, false, 80),
  ('packaging', 'packaging_type', 'Packaging type', 'text', '[]'::jsonb, false, 10),
  ('packaging', 'packaging_material', 'Packaging material', 'text', '[]'::jsonb, false, 20),
  ('packaging', 'packaging_use', 'Sales or shipping packaging', 'select', '["Sales packaging","Shipping packaging","Both","Not sure"]'::jsonb, false, 30),
  ('packaging', 'packaging_quantity', 'Estimated yearly packaging quantity', 'text', '[]'::jsonb, false, 40),
  ('packaging', 'lucid_number', 'Existing LUCID number?', 'yes_no', '[]'::jsonb, false, 50),
  ('packaging', 'system_participation', 'Existing system participation?', 'yes_no', '[]'::jsonb, false, 60),
  ('packaging', 'marketplace_used', 'Marketplace used', 'multiselect', '["Amazon","Temu","AliExpress","eBay","Shopify","Other"]'::jsonb, false, 70),
  ('gpsr', 'gpsr_product_category', 'Product category', 'text', '[]'::jsonb, false, 5),
  ('gpsr', 'manufacturer_name', 'Manufacturer name', 'text', '[]'::jsonb, false, 10),
  ('gpsr', 'manufacturer_address', 'Manufacturer address', 'textarea', '[]'::jsonb, false, 20),
  ('gpsr', 'doc_available', 'Declaration of Conformity available?', 'yes_no', '[]'::jsonb, false, 30),
  ('gpsr', 'test_reports_available', 'Test reports available?', 'yes_no', '[]'::jsonb, false, 40),
  ('gpsr', 'manual_available', 'User manual available?', 'yes_no', '[]'::jsonb, false, 50),
  ('gpsr', 'risk_assessment_available', 'Risk assessment available?', 'yes_no', '[]'::jsonb, false, 60),
  ('gpsr', 'marketplace_link', 'Marketplace link', 'text', '[]'::jsonb, false, 70),
  ('gpsr', 'urgent_case', 'Urgent authority or marketplace case?', 'yes_no', '[]'::jsonb, false, 80),
  ('gpsr', 'case_deadline', 'Case deadline', 'date', '[]'::jsonb, false, 90),
  ('warehouse', 'warehouse_product_type', 'Product type', 'text', '[]'::jsonb, false, 5),
  ('warehouse', 'cartons', 'Number of cartons', 'number', '[]'::jsonb, false, 10),
  ('warehouse', 'pallets', 'Number of pallets', 'number', '[]'::jsonb, false, 20),
  ('warehouse', 'unit_dimensions', 'Unit dimensions', 'text', '[]'::jsonb, false, 30),
  ('warehouse', 'carton_dimensions', 'Carton dimensions', 'text', '[]'::jsonb, false, 40),
  ('warehouse', 'unit_weight', 'Weight per unit', 'text', '[]'::jsonb, false, 50),
  ('warehouse', 'carton_weight', 'Weight per carton', 'text', '[]'::jsonb, false, 60),
  ('warehouse', 'storage_duration', 'Storage duration', 'text', '[]'::jsonb, false, 70),
  ('warehouse', 'delivery_date', 'Delivery date', 'date', '[]'::jsonb, false, 80),
  ('warehouse', 'forwarding_details', 'Pickup / forwarding details', 'textarea', '[]'::jsonb, false, 90),
  ('warehouse', 'inspection_needed', 'Need product inspection?', 'yes_no', '[]'::jsonb, false, 100),
  ('warehouse', 'packing_needed', 'Need packing?', 'yes_no', '[]'::jsonb, false, 110),
  ('warehouse', 'repacking_needed', 'Need repacking?', 'yes_no', '[]'::jsonb, false, 120),
  ('warehouse', 'relabeling_needed', 'Need relabeling?', 'yes_no', '[]'::jsonb, false, 130),
  ('warehouse', 'shipping_prep_needed', 'Need shipping preparation?', 'yes_no', '[]'::jsonb, false, 140),
  ('relabeling', 'units', 'Number of units', 'number', '[]'::jsonb, false, 10),
  ('relabeling', 'label_type', 'Label type', 'select', '["Barcode","FNSKU","Product label","Warning label","Other"]'::jsonb, false, 20),
  ('relabeling', 'current_label_issue', 'Current label issue', 'textarea', '[]'::jsonb, false, 30),
  ('relabeling', 'label_design_needed', 'Need label design?', 'yes_no', '[]'::jsonb, false, 40),
  ('relabeling', 'label_file', 'Upload label file', 'file', '[]'::jsonb, false, 50),
  ('relabeling', 'label_deadline', 'Deadline', 'date', '[]'::jsonb, false, 60),
  ('marketplace', 'marketplace_name', 'Marketplace name', 'select', '["Amazon","Temu","AliExpress","eBay","Shopify","Other"]'::jsonb, false, 10),
  ('marketplace', 'seller_account_country', 'Seller account country', 'text', '[]'::jsonb, false, 20),
  ('marketplace', 'product_link', 'Product link', 'text', '[]'::jsonb, false, 30),
  ('marketplace', 'item_id', 'ASIN / item ID / SKU', 'text', '[]'::jsonb, false, 40),
  ('marketplace', 'case_id', 'Case ID', 'text', '[]'::jsonb, false, 50),
  ('marketplace', 'issue_reason', 'Reason for issue', 'textarea', '[]'::jsonb, false, 60),
  ('marketplace', 'deadline', 'Deadline', 'date', '[]'::jsonb, false, 70),
  ('marketplace', 'requested_documents', 'Documents requested by marketplace', 'textarea', '[]'::jsonb, false, 80)
),
service_templates(service_slug, template) as (
  values
  ('company-formation-germany', 'formation'),
  ('german-business-address', 'formation'),
  ('vat-registration-germany', 'vat'),
  ('bookkeeping-tax-coordination', 'vat'),
  ('marketplace-seller-setup', 'marketplace'),
  ('weee-elektrog-registration', 'weee'),
  ('battery-battg-registration', 'battery'),
  ('packaging-verpackg-lucid', 'packaging'),
  ('gpsr-eu-responsible-person', 'gpsr'),
  ('product-compliance-review', 'gpsr'),
  ('declaration-of-conformity-review', 'gpsr'),
  ('test-report-review', 'gpsr'),
  ('marketplace-compliance-support', 'marketplace'),
  ('authority-case-support', 'marketplace'),
  ('warehouse-storage-germany', 'warehouse'),
  ('packing-service', 'warehouse'),
  ('repacking-umverpackung', 'warehouse'),
  ('relabeling-umlabeln', 'relabeling'),
  ('barcode-fnsku-labeling', 'relabeling'),
  ('product-inspection', 'warehouse'),
  ('return-handling', 'warehouse'),
  ('shipment-preparation', 'warehouse'),
  ('amazon-compliance-support', 'marketplace'),
  ('temu-compliance-support', 'marketplace'),
  ('aliexpress-support', 'marketplace'),
  ('ebay-support', 'marketplace'),
  ('shopify-support', 'marketplace'),
  ('product-listing-document-support', 'marketplace'),
  ('marketplace-suspension-support', 'marketplace')
)
insert into public.service_questions
  (service_slug, question_key, label, question_type, options, required, display_order)
select st.service_slug, tq.question_key, tq.label, tq.question_type, tq.options, tq.required, tq.display_order
from service_templates st
join template_questions tq on tq.template = st.template
on conflict (service_slug, question_key) do update set
  label = excluded.label,
  question_type = excluded.question_type,
  options = excluded.options,
  required = excluded.required,
  display_order = excluded.display_order,
  updated_at = now();

with document_template_sets(template, document_key, title, category, description, required_by_default, conditional_rule, accepted_file_types, example_description, sort_order) as (
  values
  ('formation', 'founder_id', 'Founder passport / ID', 'Company Documents', 'Passport or national ID for each founder or managing director.', true, null::jsonb, array['pdf','jpg','jpeg','png'], 'Use clear color scans or photos.', 10),
  ('formation', 'founder_address', 'Founder address', 'Company Documents', 'Current residential address or proof of address for founder identity checks.', true, null::jsonb, array['pdf','jpg','jpeg','png'], null, 20),
  ('formation', 'desired_company_name', 'Desired company name', 'Company Documents', 'Preferred German company name options for availability review.', true, null::jsonb, null::text[], null, 30),
  ('formation', 'business_activity', 'Business activity description', 'Company Documents', 'Clear description of the planned German business activity.', true, null::jsonb, null::text[], null, 40),
  ('formation', 'shareholder_details', 'Shareholder details', 'Company Documents', 'Names, nationalities, ownership percentages, and roles of shareholders.', true, null::jsonb, null::text[], null, 50),
  ('formation', 'german_business_address', 'German business address requirement', 'Company Documents', 'Information about whether a German address is needed for setup or correspondence.', false, '{"requiredWhen":["company_formation"]}'::jsonb, null::text[], null, 60),
  ('formation', 'vat_registration_info', 'VAT registration information', 'Tax / VAT Documents', 'VAT need, sales channels, and expected launch date for tax coordination.', false, '{"requiredWhen":["vat"]}'::jsonb, null::text[], null, 70),
  ('formation', 'power_of_attorney', 'Power of attorney if applicable', 'Company Documents', 'Authorization document if Globalflowa or partners coordinate steps on your behalf.', false, null::jsonb, array['pdf'], null, 80),

  ('vat', 'business_registration', 'Company registration document', 'Company Documents', 'Official company registration, business license, or equivalent document.', true, null::jsonb, array['pdf','jpg','jpeg','png'], null, 10),
  ('vat', 'founder_id', 'Founder/director ID', 'Company Documents', 'Passport or ID of the founder, director, or responsible representative.', true, null::jsonb, array['pdf','jpg','jpeg','png'], null, 20),
  ('vat', 'existing_vat_tax_number', 'Existing VAT/tax number if available', 'Tax / VAT Documents', 'Existing local VAT, tax, or company tax number.', false, null::jsonb, null::text[], null, 30),
  ('vat', 'marketplace_seller_info', 'Marketplace seller account information', 'Marketplace Documents', 'Seller account country, store links, and marketplace account details.', false, '{"requiredWhen":["marketplace"]}'::jsonb, null::text[], null, 40),
  ('vat', 'sales_estimate', 'Sales estimate', 'Tax / VAT Documents', 'Estimated monthly and yearly sales volumes for Germany.', true, null::jsonb, null::text[], null, 50),
  ('vat', 'bookkeeping_records', 'Bookkeeping records if applicable', 'Tax / VAT Documents', 'Existing transaction reports, bookkeeping exports, or tax advisor information.', false, null::jsonb, array['pdf','xlsx','csv'], null, 60),

  ('weee', 'business_registration', 'Business license / company registration', 'Company Documents', 'Company registration evidence for producer or seller identity.', true, null::jsonb, array['pdf','jpg','jpeg','png'], null, 10),
  ('weee', 'brand_list', 'Brand name list', 'Compliance Documents', 'Brand names used on electrical or electronic products sold in Germany.', true, null::jsonb, null::text[], null, 20),
  ('weee', 'product_photos', 'Product photos', 'Product Documents', 'Clear product photos showing the product and key components.', true, null::jsonb, array['jpg','jpeg','png','zip'], null, 30),
  ('weee', 'label_photos', 'Product label photos', 'Product Documents', 'Photos of product labels, rating plates, packaging labels, and brand markings.', true, null::jsonb, array['jpg','jpeg','png','zip'], null, 40),
  ('weee', 'user_manual', 'User manual', 'Product Documents', 'User manual or instruction sheet provided with the product.', true, null::jsonb, array['pdf','doc','docx'], null, 50),
  ('weee', 'technical_description', 'Technical product description', 'Product Documents', 'Short technical description, device type, power source, and use case.', true, null::jsonb, null::text[], null, 60),
  ('weee', 'yearly_quantity', 'Estimated yearly quantity', 'Compliance Documents', 'Expected annual quantity placed on the German market.', true, null::jsonb, null::text[], null, 70),
  ('weee', 'existing_weee_number', 'Existing WEEE number if available', 'Compliance Documents', 'Existing WEEE registration number or evidence, if already registered.', false, null::jsonb, array['pdf'], null, 80),
  ('weee', 'battery_info', 'Battery information if product contains battery', 'Compliance Documents', 'Battery type, chemistry, weight, and whether it is built in or separate.', false, '{"includeWhen":["battery"],"requiredWhen":["battery"]}'::jsonb, null::text[], null, 90),

  ('battery', 'business_registration', 'Business license / company registration', 'Company Documents', 'Company registration evidence for producer or seller identity.', true, null::jsonb, array['pdf','jpg','jpeg','png'], null, 10),
  ('battery', 'battery_type', 'Battery type information', 'Compliance Documents', 'Battery type, installation method, and whether batteries are built in or separate.', true, null::jsonb, null::text[], null, 20),
  ('battery', 'battery_chemistry', 'Battery chemistry information', 'Compliance Documents', 'Chemistry such as lithium-ion, alkaline, NiMH, or another type.', true, null::jsonb, null::text[], null, 30),
  ('battery', 'battery_weight', 'Battery weight per unit', 'Compliance Documents', 'Battery weight per unit or per product set.', true, null::jsonb, null::text[], null, 40),
  ('battery', 'product_photos', 'Product photos', 'Product Documents', 'Product photos showing the battery-powered item or battery packaging.', true, null::jsonb, array['jpg','jpeg','png','zip'], null, 50),
  ('battery', 'label_photos', 'Product label photos', 'Product Documents', 'Battery or product label photos showing markings and warnings.', true, null::jsonb, array['jpg','jpeg','png','zip'], null, 60),
  ('battery', 'battery_quantity', 'Estimated yearly battery quantity', 'Compliance Documents', 'Expected yearly battery quantity placed on the German market.', true, null::jsonb, null::text[], null, 70),
  ('battery', 'existing_battery_registration', 'Existing battery registration if available', 'Compliance Documents', 'Existing BattG registration evidence or number, if already registered.', false, null::jsonb, array['pdf'], null, 80),

  ('packaging', 'business_registration', 'Business license / company registration', 'Company Documents', 'Company registration evidence for LUCID and system participation intake.', true, null::jsonb, array['pdf','jpg','jpeg','png'], null, 10),
  ('packaging', 'packaging_material', 'Packaging material information', 'Compliance Documents', 'Packaging materials such as paper, cardboard, plastic, glass, or metal.', true, null::jsonb, null::text[], null, 20),
  ('packaging', 'packaging_quantity', 'Packaging quantity estimate', 'Compliance Documents', 'Estimated yearly packaging quantities by material.', true, null::jsonb, null::text[], null, 30),
  ('packaging', 'existing_lucid_number', 'Existing LUCID number if available', 'Compliance Documents', 'Existing LUCID registration number or evidence, if already registered.', false, null::jsonb, array['pdf'], null, 40),
  ('packaging', 'system_participation_contract', 'Existing system participation contract if available', 'Compliance Documents', 'Existing system participation contract or certificate, if already arranged.', false, null::jsonb, array['pdf'], null, 50),
  ('packaging', 'marketplace_seller_info', 'Marketplace seller information', 'Marketplace Documents', 'Marketplace names, seller account country, and listing/store links.', false, '{"requiredWhen":["marketplace"]}'::jsonb, null::text[], null, 60),

  ('gpsr', 'business_registration', 'Business license / manufacturer information', 'Company Documents', 'Company or manufacturer identity information for document review.', true, null::jsonb, array['pdf','jpg','jpeg','png'], null, 10),
  ('gpsr', 'product_photos', 'Product photos', 'Product Documents', 'Clear product photos from relevant angles.', true, null::jsonb, array['jpg','jpeg','png','zip'], null, 20),
  ('gpsr', 'label_photos', 'Product label photos', 'Product Documents', 'Label and packaging photos showing safety, traceability, importer, and manufacturer details.', true, null::jsonb, array['jpg','jpeg','png','zip'], null, 30),
  ('gpsr', 'declaration_of_conformity', 'Declaration of Conformity if applicable', 'Compliance Documents', 'Declaration of Conformity for products where EU harmonization rules apply.', false, '{"requiredWhen":["electronics"]}'::jsonb, array['pdf'], null, 40),
  ('gpsr', 'test_reports', 'Test reports', 'Compliance Documents', 'Relevant test reports and certificates matching the product model.', false, '{"requiredWhen":["electronics"]}'::jsonb, array['pdf'], null, 50),
  ('gpsr', 'user_manual', 'User manual', 'Product Documents', 'User manual, safety instructions, and language versions currently available.', true, null::jsonb, array['pdf','doc','docx'], null, 60),
  ('gpsr', 'risk_assessment', 'Risk assessment if available', 'Compliance Documents', 'Risk assessment, safety file, or product safety analysis if available.', false, null::jsonb, array['pdf','doc','docx'], null, 70),
  ('gpsr', 'manufacturer_address', 'Manufacturer address', 'Company Documents', 'Full manufacturer name and address.', true, null::jsonb, null::text[], null, 80),
  ('gpsr', 'product_category', 'Product category information', 'Product Documents', 'Product category, intended use, and target customer group.', true, null::jsonb, null::text[], null, 90),
  ('gpsr', 'marketplace_link', 'Marketplace link', 'Marketplace Documents', 'Marketplace product link, ASIN, SKU, or listing URL.', false, '{"requiredWhen":["marketplace"]}'::jsonb, null::text[], null, 100),
  ('gpsr', 'marketplace_notice', 'Authority/marketplace notice if urgent case', 'Marketplace Documents', 'Screenshots, emails, or notices showing the request and deadline.', false, '{"includeWhen":["urgent_case"],"requiredWhen":["urgent_case"]}'::jsonb, array['pdf','jpg','jpeg','png'], null, 110),

  ('warehouse', 'product_list', 'Product list', 'Warehouse Documents', 'List of products, SKUs, and quantities included in the inbound stock.', true, null::jsonb, array['pdf','xlsx','csv'], null, 10),
  ('warehouse', 'packing_list', 'Carton list', 'Warehouse Documents', 'Carton list or packing list with carton counts and contents.', true, null::jsonb, array['pdf','xlsx','csv'], null, 20),
  ('warehouse', 'pallet_info', 'Pallet information', 'Warehouse Documents', 'Pallet counts, pallet type, dimensions, and stacking notes.', false, null::jsonb, null::text[], null, 30),
  ('warehouse', 'product_dimensions', 'Product dimensions', 'Warehouse Documents', 'Unit dimensions and carton dimensions.', true, null::jsonb, null::text[], null, 40),
  ('warehouse', 'product_weight', 'Product weight', 'Warehouse Documents', 'Unit and carton weights.', true, null::jsonb, null::text[], null, 50),
  ('warehouse', 'delivery_notice', 'Delivery notice', 'Warehouse Documents', 'Inbound delivery date, carrier details, and appointment or tracking information.', true, null::jsonb, array['pdf','jpg','jpeg','png'], null, 60),
  ('warehouse', 'shipping_marks', 'Shipping marks', 'Warehouse Documents', 'Carton or pallet shipping marks and external labels.', false, null::jsonb, array['pdf','jpg','jpeg','png'], null, 70),
  ('warehouse', 'packing_instructions', 'Packing instructions', 'Warehouse Documents', 'Packing, inspection, repacking, or handling instructions.', false, null::jsonb, null::text[], null, 80),
  ('warehouse', 'relabeling_instructions', 'Relabeling instructions if needed', 'Warehouse Documents', 'Relabeling scope, placement rules, and label matching instructions.', false, '{"includeWhen":["relabeling"],"requiredWhen":["relabeling"]}'::jsonb, null::text[], null, 90),

  ('relabeling', 'label_file', 'Label file', 'Warehouse Documents', 'Final label PDF, barcode, FNSKU, or product label file.', true, null::jsonb, array['pdf','png','jpg','jpeg'], null, 10),
  ('relabeling', 'barcode_list', 'Barcode / FNSKU list', 'Warehouse Documents', 'SKU, ASIN, barcode, or FNSKU list mapped to each product.', true, null::jsonb, array['pdf','xlsx','csv'], null, 20),
  ('relabeling', 'product_photos', 'Product photos', 'Product Documents', 'Product photos used to confirm label placement.', true, null::jsonb, array['jpg','jpeg','png','zip'], null, 30),
  ('relabeling', 'label_photos', 'Current label photos', 'Product Documents', 'Photos of current labels and label issues.', true, null::jsonb, array['jpg','jpeg','png','zip'], null, 40),
  ('relabeling', 'quantity_list', 'Quantity list', 'Warehouse Documents', 'Unit quantity by SKU or carton for relabeling work.', true, null::jsonb, array['pdf','xlsx','csv'], null, 50),
  ('relabeling', 'deadline_info', 'Deadline information', 'Warehouse Documents', 'Marketplace, carrier, or launch deadline for relabeling.', false, '{"requiredWhen":["urgent_case"]}'::jsonb, null::text[], null, 60),

  ('marketplace', 'marketplace_notice', 'Marketplace notice screenshot', 'Marketplace Documents', 'Screenshot, email, or notice from the marketplace showing the issue.', false, '{"requiredWhen":["urgent_case","marketplace"]}'::jsonb, array['pdf','jpg','jpeg','png'], null, 10),
  ('marketplace', 'product_link', 'Product link', 'Marketplace Documents', 'Product listing URL or marketplace link.', true, null::jsonb, null::text[], null, 20),
  ('marketplace', 'asin_sku_item_id', 'ASIN / SKU / item ID', 'Marketplace Documents', 'ASIN, SKU, item ID, or listing identifier for the affected product.', true, null::jsonb, null::text[], null, 30),
  ('marketplace', 'case_id', 'Case ID', 'Marketplace Documents', 'Marketplace case, ticket, or support ID if available.', false, null::jsonb, null::text[], null, 40),
  ('marketplace', 'requested_documents', 'Requested documents list', 'Marketplace Documents', 'List of documents requested by the marketplace.', true, null::jsonb, null::text[], null, 50),
  ('marketplace', 'marketplace_communication', 'Previous communication with marketplace', 'Marketplace Documents', 'Emails, chat screenshots, or marketplace support messages.', false, null::jsonb, array['pdf','jpg','jpeg','png'], null, 60),
  ('marketplace', 'deadline_info', 'Deadline information', 'Marketplace Documents', 'Deadline or response date stated by the marketplace.', false, '{"requiredWhen":["urgent_case"]}'::jsonb, null::text[], null, 70)
),
document_service_templates(service_slug, template) as (
  values
  ('company-formation-germany', 'formation'),
  ('german-business-address', 'formation'),
  ('vat-registration-germany', 'vat'),
  ('bookkeeping-tax-coordination', 'vat'),
  ('marketplace-seller-setup', 'marketplace'),
  ('weee-elektrog-registration', 'weee'),
  ('battery-battg-registration', 'battery'),
  ('packaging-verpackg-lucid', 'packaging'),
  ('gpsr-eu-responsible-person', 'gpsr'),
  ('product-compliance-review', 'gpsr'),
  ('declaration-of-conformity-review', 'gpsr'),
  ('test-report-review', 'gpsr'),
  ('marketplace-compliance-support', 'marketplace'),
  ('authority-case-support', 'marketplace'),
  ('warehouse-storage-germany', 'warehouse'),
  ('packing-service', 'warehouse'),
  ('repacking-umverpackung', 'warehouse'),
  ('relabeling-umlabeln', 'relabeling'),
  ('barcode-fnsku-labeling', 'relabeling'),
  ('product-inspection', 'warehouse'),
  ('return-handling', 'warehouse'),
  ('shipment-preparation', 'warehouse'),
  ('amazon-compliance-support', 'marketplace'),
  ('temu-compliance-support', 'marketplace'),
  ('aliexpress-support', 'marketplace'),
  ('ebay-support', 'marketplace'),
  ('shopify-support', 'marketplace'),
  ('product-listing-document-support', 'marketplace'),
  ('marketplace-suspension-support', 'marketplace')
)
insert into public.document_templates
  (service_slug, document_key, title, category, description, required_by_default, conditional_rule, accepted_file_types, example_description, sort_order, is_active)
select dst.service_slug, dts.document_key, dts.title, dts.category, dts.description, dts.required_by_default, dts.conditional_rule, dts.accepted_file_types, dts.example_description, dts.sort_order, true
from document_service_templates dst
join document_template_sets dts on dts.template = dst.template
on conflict (service_slug, document_key) do update set
  title = excluded.title,
  category = excluded.category,
  description = excluded.description,
  required_by_default = excluded.required_by_default,
  conditional_rule = excluded.conditional_rule,
  accepted_file_types = excluded.accepted_file_types,
  example_description = excluded.example_description,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();
