"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { editableLifecycleStages, lifecycleInfo, normalizeLifecycleStage } from "@/lib/request-lifecycle";

export function CustomerLifecycleProgress({ requestId, initialStage, updatedAt }: { requestId: string; initialStage: string | null; updatedAt: string | null }) {
  const router = useRouter(); const [stage, setStage] = useState(normalizeLifecycleStage(initialStage)); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function save() { setSaving(true); setMessage(null); try { const response = await fetch("/api/admin/request-lifecycle", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ request_id: requestId, lifecycle_stage: stage }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error); setMessage("Customer lifecycle stage updated."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update lifecycle stage."); } finally { setSaving(false); } }
  const terminal = ["completed", "archived"].includes(normalizeLifecycleStage(initialStage));
  return <section className="rounded-md border border-teal-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold text-navy-950">Customer Lifecycle Progress</h2><p className="mt-2 text-sm text-navy-650">Separate from the internal operational status. This is the progress customers see.</p><div className="mt-5 grid gap-4 md:grid-cols-2">{terminal ? <div><p className="text-sm font-semibold text-navy-950">Lifecycle stage</p><p className="mt-2 text-sm text-navy-650">Terminal states are changed only through the completion and archive controls.</p></div> : <label><span className="text-sm font-semibold text-navy-950">Lifecycle stage</span><select value={stage} onChange={(event) => setStage(normalizeLifecycleStage(event.target.value))} className="mt-2 w-full rounded-md border border-navy-200 px-3 py-2">{editableLifecycleStages.map((item) => <option key={item} value={item}>{lifecycleInfo[item].label}</option>)}</select></label>}<div className="rounded-md bg-navy-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-teal-700">Customer-visible preview</p><p className="mt-2 font-semibold text-navy-950">{lifecycleInfo[stage].label}</p><p className="mt-1 text-sm text-navy-650">{lifecycleInfo[stage].description}</p></div></div><p className="mt-4 text-sm text-navy-650">{lifecycleInfo[stage].next}</p>{updatedAt ? <p className="mt-2 text-xs text-navy-500">Last updated {new Date(updatedAt).toLocaleString()}</p> : null}{!terminal ? <button type="button" onClick={save} disabled={saving} className="mt-5 rounded-md bg-navy-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Updating..." : "Update customer lifecycle"}</button> : null}{message ? <p className="mt-3 text-sm text-teal-700" role="status">{message}</p> : null}</section>;
}
